
- name: "Enable required cgroup features"
  become: true
  lineinfile:
    path: /boot/firmware/nobtcmd.txt
    backrefs: True
    regexp: '(^.+fixrtc(\s+(?!cgroup_enable=memory cgroup_memory=1)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=memory cgroup_memory=1'
    state: present
  register: cgroup_result
#
# - name: "Reboot if cgroup features changed"
#   become: true
#   reboot:
#   when: cgroup_result is changed
#
# # sudo snap install microk8s --classic --channel=1.18/stable
# - name: "Install MicroK8s via snap"
#   become: true
#   snap:
#     name: "microk8s"
#     channel: "1.18/stable"
#     classic: true
