# DickM
# This is a defined localhost inventory file.
# So that target=localhost actually runs on the localhost.

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: python
    pi-4-1:
      ansible_host: 192.168.1.135
      ansible_user: ubuntu
      ansible_password: Fred1405
  pi:
    children:
      pi-4-1:
